create database whatsapp;
use whatsapp;
create table user;
create table user(uid int,username varchar(255),status varchar(255),number varchar(255));
insert into user values(1,"raghu","i am using whatsapp","8015133968");
select * from user;
create table friends(fid int,friendname varchar(255),groupname varchar(255) primary key(fid));
create table friends(fid int,friendname varchar(255),groupname varchar(255),primary key(fid));
insert into friends(1,"mani","family");
insert into friends values(1,"mani","family");
select * from friends;
create table sent(sentid varchar(255),message varchar(255),id int,foreign key(id) references friends(fid)); 
insert into sent values("1","hi dad",1);
select * from sent;
create table recieve(recieveid varchar(255),message varchar(255),id int,foreign key(id) references friends(fid),primary key(recieveid));
insert into recieve values("1","hi raghu",1);
select * from recieve;
create table mediasent(mediaid varchar(255),audio int,video int,pdf int,mid varchar(255),foreign key(mid) references sent(sentid),primary key(mediaid));
create table mediasent(mediaid varchar(255),audio int,video int,pdf int,mid varchar(255),foreign key (mid) references sent (sentid),primary key(mediaid));
create table mediasent(mediaid varchar(255),audio int,video int,pdf int,mid varchar(255),foreign key (mid) references recieve (recieveid),primary key(mediaid));
alter table sent add primary key(sentid);
rename table mediasent to mediarecieve;
create table mediasent(mediaid varchar(255),audio int,video int,pdf int,mid varchar(255),foreign key (mid) references recieve (recieveid),primary key(mediaid));
select * from recieve;
create table files(mediaid varchar(255),audio varchar(255),video varchar(255),pdf create table filesent(mediaid varchar(255),audio varchar(255),video varchar(255),pdf varchar(255),mid int,foreign key (mid) references friends (fid),primary key(mediaid));
create table filessent(mediaid varchar(255),audio varchar(255),video varchar(255),pdf varchar(255),mid int,foreign key (mid) references friends (fid),primary key(mediaid));
drop table filereceived;
show tables;
rename table filessent to mediasent;
rename table files to mediarecieve;
select * from sent;
select * from recieve;
rename table sent to textsent;
rename table recieve to textrecive;
show tables;
insert into mediasent values("m1","audio.mp3",null,null,1);
select * from mediasent;
insert into mediarecieve values("m11",null,"asd.mp4",null,1);
select * from mediarecieve;
insert into mediarecieve values("m12",null,"asd2.mp4",null,1);
select * from mediarecieve;
select * from mediarecieve where mid=1;
select * from mediarecieve where mid="1";
select * from mediarecieve;
use whatsapp;
select * from mediarecieve;
select * from mediarecieve where mediaid="1";
select * from mediarecieve where mediaid="m11";
select * from friends;
insert into friends values(2,"mathi",friends);
insert into friends values(2,"mathi","friends");
insert into friends values(3,"lr","friends");
insert into friends values(3,"vignesh","friends");
insert into friends values(4,"vignesh","friends");
insert into friends values(5,"messi","sports");
select * from mediarecieve;
insert into mediarecieve (mediaida,audio,mid);
insert into mediarecieve (mediaida,audio,mid) values ("m13","nanban.mp3",3);
insert into mediarecieve (mediaid,audio,mid) values ("m13","nanban.mp3",3);
insert into mediarecieve (mediaid,audio,mid) values ("m14","kad.mp3",3);
insert into mediarecieve (mediaid,pdf,mid) values ("m15","sql.docx",3);
select * from mediarecieve;
select * from mediarecieve where mid=3;
select audio from mediarecieve where mid=3;
select * from user;
alter table user add column lastseen datetime default current_timestamp;
select * from user;
update table user set lastseen=getdate() where uid=1;
update table user set lastseen=now() where uid=1;
update user set lastseen=now() where uid=1;
select * from user;
show tables;
alter table friends add column lastseen datetime default current_timestamp;
select * from friends;
update friends set lastseen=now() where fid=3;
select * from friends;
show tables;
alter table textsent add column time datetime default current_timestamp;
select * from textsent;
insert into textsent values(2,"hiiiiii",1);
insert into textsent values("2","hiiiiii",1);
insert into textsent values("2","hiiiiii",1,now());
select * from textsent;
show tables;
alter table textrecive add column time datetime default current_timestamp;
select * from textrecive;
select * from mediarecieve;
alter table mediarecieve add column time datetime default current_timestamp;
show tables;
alter table mediasent add column time datetime default current_timestamp;
select * from mediasent;
create table dailyinfo;
select * into dailyinfo from user;
select * from mediasent; 
insert into mediasent(mediaid,pdf,mid,time) values("m12","js.pdf",4);
insert into mediasent(mediaid,pdf,mid,time) values("m12","js.pdf","4");
insert into mediasent(mediaid,pdf,mid,time) values("m12","js.pdf",4,now());
insert into mediasent(mediaid,pdf,mid,time) values("m13","java.pdf",5,now());
insert into mediasent(mediaid,video,mid,time) values("m14","cric.mp4",2,now());
select * from mediasent;
select friends.name from friends inner join mediasent on mid=fid;
select friends.name from friends inner join mediasent on mediasent.mid=friends.fid;
select * from friends;
select friends.friendname from friends inner join mediasent on mediasent.mid=friends.fid;
select column_name,data_type FROM COLUMNS WHERE TABLE_NAME="friends" and table_schema="whatsapp";
select column_name,data_type FROM COLUMNS WHERE TABLE_NAME="friends" and table_schema="whatsapp";
select information_schema.columns where column_name="friends";
select information_schema.columns where column name="friends";
select information_schema.columns ;
select information_schema.columns from information_schema;
select column_name from columns where table-name="friends" and table_schema="whatsapp";
select column_name from columns where table-name="friends" and table_schema="information_schema";
select information_schema.column_name from information_schema;
select information_schema.column_name;
show information_schema.column_name;
show information_schema.columns;
use information_schema;
show whatsap.tables;
show whatsapp.tables;
show tables in whatsapp;
select columns in whatsapp.friends;
select 'column_name' from 'information_schema'.'columns' where table_schema="whatsapp" and table_name="friends";
select 'column_name' from information_schema.columns where table_schema="whatsapp" and table_name="friends";
select column_name from information_schema.columns where table_schema="whatsapp" and table_name="friends";
use whatsapp
show tables;
insert into user values(2,"mani","hi","9943974658");
select * from user;
insert into user values(2,"mani","hi","9943974658",now());
select * from friends;
alter table friends add id varchar(255);
alter table friends add foreign key(id) references user(uid);
insert into friends 
(id=1) where fid=1;
insert into friends  (id=1) where fid=1;
insert into friends  (id) values(1) where fid=1;
alter table friends drop column id;
alter table friends add id int;
alter table friends add foreign key(id) references user(uid);
update friends set id=1 where fid=1;
update friends set id=1 where fid=2;
update friends set id=1 where fid=3;
update friends set id=1 where fid=4;
update friends set id=1 where fid=5;
alter table friends add foreign key(id) references user(uid);
select * from textsent;
insert into textsent("3","asdf",2,now());
insert into textsent(3,"asdf",2,now());
insert into textsent("3","asdf","2",now());
insert into textsent("3","asdf",1,now());
insert into textsent(3,"asdf",1,now());
insert into textsent values("3","asdf",1,now());
select * from textsent;
